module.exports = [
	"Unknown",
	"Position Report Class A",
	"Position Report Class A (Assigned schedule)",
	"Position Report Class A (Response to interrogation)",
	"Base Station Report",
	"Static and Voyage Related Data",
	"Binary Addressed Message",
	"Binary Acknowledge",
	"Binary Broadcast Message",
	"Standard SAR Aircraft Position Report",
	"UTC and Date Inquiry",
	"UTC and Date Response",
	"Addressed Safety Related Message",
	"Safety Related Acknowledgement",
	"Safety Related Broadcast Message",
	"Interrogation",
	"Assignment Mode Command",
	"DGNSS Binary Broadcast Message",
	"Standard Class B CS Position Report",
	"Extended Class B Equipment Position Report",
	"Data Link Management",
	"Aid-to-Navigation Report",
	"Channel Management",
	"Group Assignment Command",
	"Static Data Report",
	"Single Slot Binary Message,",
	"Multiple Slot Binary Message With Communications State",
	"Position Report For Long-Range Applications"
];
